version: "3.3"
services:
  nodejs:
    build: 
      context: .
    image: lemon
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=mysql-con
      - MYSQL_USER=aiman
      - MYSQL_PASS=password
      - MYSQL_DB=mydb
    volumes:
      - $PWD:/var/www/html/
    ports:
      - "8081:8087"
    container_name: nodejs-con
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=aiman
      - MYSQL_PASSWORD=password 
      - MYSQL_DATABASE=mydb
    container_name: mysql-con
networks:
  frontend:
  backend:
