version: "3.8"
services:

  nginx:
    build:
      context: ./nginx
    image: nginx:img
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - nodejs
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
      - backend
  

  nodejs:
    build: 
      context: ./app
    image: lemon
   
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=mysql-con
      - MYSQL_USER=aiman
      - MYSQL_PASS=password
      - MYSQL_DB=mydb
    volumes:
      - $PWD:/var/www/html/
    ports:
      - "5000:5000"
    container_name: nodejs-con
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=aiman
      - MYSQL_PASSWORD=password 
      - MYSQL_DATABASE=mydb
    container_name: mysql-con
networks:
  frontend:
  backend: